# golangci-lint v2.x 配置
# 本地使用: golangci-lint run --new-from-rev=origin/main ./...
# CI 使用: golangci-lint run --new-from-rev=origin/${CI_MERGE_REQUEST_TARGET_BRANCH_NAME} ./...

version: "2"

run:
  timeout: 10m
  concurrency: 0

linters:
  enable:
    - nestif # 检查 if 嵌套深度
    - gocognit # 检查认知复杂度
    - gocyclo # 检查圈复杂度
    - errcheck # 检查未处理的错误
    - govet # 检查可疑代码结构
    - ineffassign # 检查无效赋值
    - staticcheck # v2 中已包含 gosimple 和 stylecheck
    - unused # 检查未使用的代码

  settings:
    nestif:
      # 触发报告的最小 if 嵌套复杂度，默认值: 5
      min-complexity: 4

    gocognit:
      # 触发报告的最小认知复杂度，默认值: 30，推荐 10-20
      min-complexity: 15

    gocyclo:
      # 触发报告的最小圈复杂度，默认值: 10
      min-complexity: 10

  exclusions:
    # 排除生成文件
    generated: lax

    paths:
      - vendor
      - bin
      - ".*\\.pb\\.go$"
      - ".*\\.gen\\.go$"

    rules:
      # 测试文件放宽检查
      - path: "_test\\.go"
        linters:
          - gocyclo
          - errcheck
          - dupl
          - gosec
          - gocognit
          - nestif

issues:
  # 限制每个 linter 报告的最大问题数
  max-issues-per-linter: 50
  max-same-issues: 3
