dir: '{{.InterfaceDir}}/mocks'
structname: Mock{{.InterfaceName}}
filename: mock_{{.InterfaceName | snakecase}}.go
pkgname: mocks
template: testify
template-data:
  unroll-variadic: true
packages:
  github.com/cocursor/backend/internal/application/team:
    interfaces:
      CacheManager: {}
      HTTPClientInterface: {}
      ProjectConfigStoreInterface: {}
      TeamServiceInterface: {}
      WeeklyStatsStoreInterface: {}
