// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	mock "github.com/stretchr/testify/mock"
)

// NewMockCacheManager creates a new instance of MockCacheManager. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockCacheManager(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockCacheManager {
	mock := &MockCacheManager{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockCacheManager is an autogenerated mock type for the CacheManager type
type MockCacheManager struct {
	mock.Mock
}

type MockCacheManager_Expecter struct {
	mock *mock.Mock
}

func (_m *MockCacheManager) EXPECT() *MockCacheManager_Expecter {
	return &MockCacheManager_Expecter{mock: &_m.Mock}
}

// InvalidateMemberCache provides a mock function for the type MockCacheManager
func (_mock *MockCacheManager) InvalidateMemberCache(teamID string, memberID string) {
	_mock.Called(teamID, memberID)
	return
}

// MockCacheManager_InvalidateMemberCache_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'InvalidateMemberCache'
type MockCacheManager_InvalidateMemberCache_Call struct {
	*mock.Call
}

// InvalidateMemberCache is a helper method to define mock.On call
//   - teamID string
//   - memberID string
func (_e *MockCacheManager_Expecter) InvalidateMemberCache(teamID interface{}, memberID interface{}) *MockCacheManager_InvalidateMemberCache_Call {
	return &MockCacheManager_InvalidateMemberCache_Call{Call: _e.mock.On("InvalidateMemberCache", teamID, memberID)}
}

func (_c *MockCacheManager_InvalidateMemberCache_Call) Run(run func(teamID string, memberID string)) *MockCacheManager_InvalidateMemberCache_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockCacheManager_InvalidateMemberCache_Call) Return() *MockCacheManager_InvalidateMemberCache_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockCacheManager_InvalidateMemberCache_Call) RunAndReturn(run func(teamID string, memberID string)) *MockCacheManager_InvalidateMemberCache_Call {
	_c.Run(run)
	return _c
}

// InvalidateTeamCache provides a mock function for the type MockCacheManager
func (_mock *MockCacheManager) InvalidateTeamCache(teamID string) {
	_mock.Called(teamID)
	return
}

// MockCacheManager_InvalidateTeamCache_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'InvalidateTeamCache'
type MockCacheManager_InvalidateTeamCache_Call struct {
	*mock.Call
}

// InvalidateTeamCache is a helper method to define mock.On call
//   - teamID string
func (_e *MockCacheManager_Expecter) InvalidateTeamCache(teamID interface{}) *MockCacheManager_InvalidateTeamCache_Call {
	return &MockCacheManager_InvalidateTeamCache_Call{Call: _e.mock.On("InvalidateTeamCache", teamID)}
}

func (_c *MockCacheManager_InvalidateTeamCache_Call) Run(run func(teamID string)) *MockCacheManager_InvalidateTeamCache_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockCacheManager_InvalidateTeamCache_Call) Return() *MockCacheManager_InvalidateTeamCache_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockCacheManager_InvalidateTeamCache_Call) RunAndReturn(run func(teamID string)) *MockCacheManager_InvalidateTeamCache_Call {
	_c.Run(run)
	return _c
}
