// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"github.com/cocursor/backend/internal/domain/team"
	mock "github.com/stretchr/testify/mock"
)

// NewMockProjectConfigStoreInterface creates a new instance of MockProjectConfigStoreInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockProjectConfigStoreInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockProjectConfigStoreInterface {
	mock := &MockProjectConfigStoreInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockProjectConfigStoreInterface is an autogenerated mock type for the ProjectConfigStoreInterface type
type MockProjectConfigStoreInterface struct {
	mock.Mock
}

type MockProjectConfigStoreInterface_Expecter struct {
	mock *mock.Mock
}

func (_m *MockProjectConfigStoreInterface) EXPECT() *MockProjectConfigStoreInterface_Expecter {
	return &MockProjectConfigStoreInterface_Expecter{mock: &_m.Mock}
}

// AddProject provides a mock function for the type MockProjectConfigStoreInterface
func (_mock *MockProjectConfigStoreInterface) AddProject(project team.ProjectMatcher) error {
	ret := _mock.Called(project)

	if len(ret) == 0 {
		panic("no return value specified for AddProject")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(team.ProjectMatcher) error); ok {
		r0 = returnFunc(project)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockProjectConfigStoreInterface_AddProject_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddProject'
type MockProjectConfigStoreInterface_AddProject_Call struct {
	*mock.Call
}

// AddProject is a helper method to define mock.On call
//   - project team.ProjectMatcher
func (_e *MockProjectConfigStoreInterface_Expecter) AddProject(project interface{}) *MockProjectConfigStoreInterface_AddProject_Call {
	return &MockProjectConfigStoreInterface_AddProject_Call{Call: _e.mock.On("AddProject", project)}
}

func (_c *MockProjectConfigStoreInterface_AddProject_Call) Run(run func(project team.ProjectMatcher)) *MockProjectConfigStoreInterface_AddProject_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 team.ProjectMatcher
		if args[0] != nil {
			arg0 = args[0].(team.ProjectMatcher)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockProjectConfigStoreInterface_AddProject_Call) Return(err error) *MockProjectConfigStoreInterface_AddProject_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockProjectConfigStoreInterface_AddProject_Call) RunAndReturn(run func(project team.ProjectMatcher) error) *MockProjectConfigStoreInterface_AddProject_Call {
	_c.Call.Return(run)
	return _c
}

// GetRepoURLs provides a mock function for the type MockProjectConfigStoreInterface
func (_mock *MockProjectConfigStoreInterface) GetRepoURLs() []string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetRepoURLs")
	}

	var r0 []string
	if returnFunc, ok := ret.Get(0).(func() []string); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}
	return r0
}

// MockProjectConfigStoreInterface_GetRepoURLs_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetRepoURLs'
type MockProjectConfigStoreInterface_GetRepoURLs_Call struct {
	*mock.Call
}

// GetRepoURLs is a helper method to define mock.On call
func (_e *MockProjectConfigStoreInterface_Expecter) GetRepoURLs() *MockProjectConfigStoreInterface_GetRepoURLs_Call {
	return &MockProjectConfigStoreInterface_GetRepoURLs_Call{Call: _e.mock.On("GetRepoURLs")}
}

func (_c *MockProjectConfigStoreInterface_GetRepoURLs_Call) Run(run func()) *MockProjectConfigStoreInterface_GetRepoURLs_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockProjectConfigStoreInterface_GetRepoURLs_Call) Return(strings []string) *MockProjectConfigStoreInterface_GetRepoURLs_Call {
	_c.Call.Return(strings)
	return _c
}

func (_c *MockProjectConfigStoreInterface_GetRepoURLs_Call) RunAndReturn(run func() []string) *MockProjectConfigStoreInterface_GetRepoURLs_Call {
	_c.Call.Return(run)
	return _c
}

// Load provides a mock function for the type MockProjectConfigStoreInterface
func (_mock *MockProjectConfigStoreInterface) Load() (*team.TeamProjectConfig, error) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Load")
	}

	var r0 *team.TeamProjectConfig
	var r1 error
	if returnFunc, ok := ret.Get(0).(func() (*team.TeamProjectConfig, error)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() *team.TeamProjectConfig); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*team.TeamProjectConfig)
		}
	}
	if returnFunc, ok := ret.Get(1).(func() error); ok {
		r1 = returnFunc()
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockProjectConfigStoreInterface_Load_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Load'
type MockProjectConfigStoreInterface_Load_Call struct {
	*mock.Call
}

// Load is a helper method to define mock.On call
func (_e *MockProjectConfigStoreInterface_Expecter) Load() *MockProjectConfigStoreInterface_Load_Call {
	return &MockProjectConfigStoreInterface_Load_Call{Call: _e.mock.On("Load")}
}

func (_c *MockProjectConfigStoreInterface_Load_Call) Run(run func()) *MockProjectConfigStoreInterface_Load_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockProjectConfigStoreInterface_Load_Call) Return(teamProjectConfig *team.TeamProjectConfig, err error) *MockProjectConfigStoreInterface_Load_Call {
	_c.Call.Return(teamProjectConfig, err)
	return _c
}

func (_c *MockProjectConfigStoreInterface_Load_Call) RunAndReturn(run func() (*team.TeamProjectConfig, error)) *MockProjectConfigStoreInterface_Load_Call {
	_c.Call.Return(run)
	return _c
}

// RemoveProject provides a mock function for the type MockProjectConfigStoreInterface
func (_mock *MockProjectConfigStoreInterface) RemoveProject(projectID string) error {
	ret := _mock.Called(projectID)

	if len(ret) == 0 {
		panic("no return value specified for RemoveProject")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(string) error); ok {
		r0 = returnFunc(projectID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockProjectConfigStoreInterface_RemoveProject_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RemoveProject'
type MockProjectConfigStoreInterface_RemoveProject_Call struct {
	*mock.Call
}

// RemoveProject is a helper method to define mock.On call
//   - projectID string
func (_e *MockProjectConfigStoreInterface_Expecter) RemoveProject(projectID interface{}) *MockProjectConfigStoreInterface_RemoveProject_Call {
	return &MockProjectConfigStoreInterface_RemoveProject_Call{Call: _e.mock.On("RemoveProject", projectID)}
}

func (_c *MockProjectConfigStoreInterface_RemoveProject_Call) Run(run func(projectID string)) *MockProjectConfigStoreInterface_RemoveProject_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockProjectConfigStoreInterface_RemoveProject_Call) Return(err error) *MockProjectConfigStoreInterface_RemoveProject_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockProjectConfigStoreInterface_RemoveProject_Call) RunAndReturn(run func(projectID string) error) *MockProjectConfigStoreInterface_RemoveProject_Call {
	_c.Call.Return(run)
	return _c
}

// Save provides a mock function for the type MockProjectConfigStoreInterface
func (_mock *MockProjectConfigStoreInterface) Save(config *team.TeamProjectConfig) error {
	ret := _mock.Called(config)

	if len(ret) == 0 {
		panic("no return value specified for Save")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(*team.TeamProjectConfig) error); ok {
		r0 = returnFunc(config)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockProjectConfigStoreInterface_Save_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Save'
type MockProjectConfigStoreInterface_Save_Call struct {
	*mock.Call
}

// Save is a helper method to define mock.On call
//   - config *team.TeamProjectConfig
func (_e *MockProjectConfigStoreInterface_Expecter) Save(config interface{}) *MockProjectConfigStoreInterface_Save_Call {
	return &MockProjectConfigStoreInterface_Save_Call{Call: _e.mock.On("Save", config)}
}

func (_c *MockProjectConfigStoreInterface_Save_Call) Run(run func(config *team.TeamProjectConfig)) *MockProjectConfigStoreInterface_Save_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *team.TeamProjectConfig
		if args[0] != nil {
			arg0 = args[0].(*team.TeamProjectConfig)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockProjectConfigStoreInterface_Save_Call) Return(err error) *MockProjectConfigStoreInterface_Save_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockProjectConfigStoreInterface_Save_Call) RunAndReturn(run func(config *team.TeamProjectConfig) error) *MockProjectConfigStoreInterface_Save_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateProject provides a mock function for the type MockProjectConfigStoreInterface
func (_mock *MockProjectConfigStoreInterface) UpdateProject(project team.ProjectMatcher) error {
	ret := _mock.Called(project)

	if len(ret) == 0 {
		panic("no return value specified for UpdateProject")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(team.ProjectMatcher) error); ok {
		r0 = returnFunc(project)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockProjectConfigStoreInterface_UpdateProject_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateProject'
type MockProjectConfigStoreInterface_UpdateProject_Call struct {
	*mock.Call
}

// UpdateProject is a helper method to define mock.On call
//   - project team.ProjectMatcher
func (_e *MockProjectConfigStoreInterface_Expecter) UpdateProject(project interface{}) *MockProjectConfigStoreInterface_UpdateProject_Call {
	return &MockProjectConfigStoreInterface_UpdateProject_Call{Call: _e.mock.On("UpdateProject", project)}
}

func (_c *MockProjectConfigStoreInterface_UpdateProject_Call) Run(run func(project team.ProjectMatcher)) *MockProjectConfigStoreInterface_UpdateProject_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 team.ProjectMatcher
		if args[0] != nil {
			arg0 = args[0].(team.ProjectMatcher)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockProjectConfigStoreInterface_UpdateProject_Call) Return(err error) *MockProjectConfigStoreInterface_UpdateProject_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockProjectConfigStoreInterface_UpdateProject_Call) RunAndReturn(run func(project team.ProjectMatcher) error) *MockProjectConfigStoreInterface_UpdateProject_Call {
	_c.Call.Return(run)
	return _c
}
