// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"time"

	"github.com/cocursor/backend/internal/domain/team"
	mock "github.com/stretchr/testify/mock"
)

// NewMockWeeklyStatsStoreInterface creates a new instance of MockWeeklyStatsStoreInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockWeeklyStatsStoreInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockWeeklyStatsStoreInterface {
	mock := &MockWeeklyStatsStoreInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockWeeklyStatsStoreInterface is an autogenerated mock type for the WeeklyStatsStoreInterface type
type MockWeeklyStatsStoreInterface struct {
	mock.Mock
}

type MockWeeklyStatsStoreInterface_Expecter struct {
	mock *mock.Mock
}

func (_m *MockWeeklyStatsStoreInterface) EXPECT() *MockWeeklyStatsStoreInterface_Expecter {
	return &MockWeeklyStatsStoreInterface_Expecter{mock: &_m.Mock}
}

// Clear provides a mock function for the type MockWeeklyStatsStoreInterface
func (_mock *MockWeeklyStatsStoreInterface) Clear() error {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Clear")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func() error); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockWeeklyStatsStoreInterface_Clear_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Clear'
type MockWeeklyStatsStoreInterface_Clear_Call struct {
	*mock.Call
}

// Clear is a helper method to define mock.On call
func (_e *MockWeeklyStatsStoreInterface_Expecter) Clear() *MockWeeklyStatsStoreInterface_Clear_Call {
	return &MockWeeklyStatsStoreInterface_Clear_Call{Call: _e.mock.On("Clear")}
}

func (_c *MockWeeklyStatsStoreInterface_Clear_Call) Run(run func()) *MockWeeklyStatsStoreInterface_Clear_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockWeeklyStatsStoreInterface_Clear_Call) Return(err error) *MockWeeklyStatsStoreInterface_Clear_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockWeeklyStatsStoreInterface_Clear_Call) RunAndReturn(run func() error) *MockWeeklyStatsStoreInterface_Clear_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function for the type MockWeeklyStatsStoreInterface
func (_mock *MockWeeklyStatsStoreInterface) Delete(memberID string, weekStart string) error {
	ret := _mock.Called(memberID, weekStart)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(string, string) error); ok {
		r0 = returnFunc(memberID, weekStart)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockWeeklyStatsStoreInterface_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockWeeklyStatsStoreInterface_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - memberID string
//   - weekStart string
func (_e *MockWeeklyStatsStoreInterface_Expecter) Delete(memberID interface{}, weekStart interface{}) *MockWeeklyStatsStoreInterface_Delete_Call {
	return &MockWeeklyStatsStoreInterface_Delete_Call{Call: _e.mock.On("Delete", memberID, weekStart)}
}

func (_c *MockWeeklyStatsStoreInterface_Delete_Call) Run(run func(memberID string, weekStart string)) *MockWeeklyStatsStoreInterface_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockWeeklyStatsStoreInterface_Delete_Call) Return(err error) *MockWeeklyStatsStoreInterface_Delete_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockWeeklyStatsStoreInterface_Delete_Call) RunAndReturn(run func(memberID string, weekStart string) error) *MockWeeklyStatsStoreInterface_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// Get provides a mock function for the type MockWeeklyStatsStoreInterface
func (_mock *MockWeeklyStatsStoreInterface) Get(memberID string, weekStart string) (*team.MemberWeeklyStats, error) {
	ret := _mock.Called(memberID, weekStart)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 *team.MemberWeeklyStats
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string, string) (*team.MemberWeeklyStats, error)); ok {
		return returnFunc(memberID, weekStart)
	}
	if returnFunc, ok := ret.Get(0).(func(string, string) *team.MemberWeeklyStats); ok {
		r0 = returnFunc(memberID, weekStart)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*team.MemberWeeklyStats)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string, string) error); ok {
		r1 = returnFunc(memberID, weekStart)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockWeeklyStatsStoreInterface_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type MockWeeklyStatsStoreInterface_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - memberID string
//   - weekStart string
func (_e *MockWeeklyStatsStoreInterface_Expecter) Get(memberID interface{}, weekStart interface{}) *MockWeeklyStatsStoreInterface_Get_Call {
	return &MockWeeklyStatsStoreInterface_Get_Call{Call: _e.mock.On("Get", memberID, weekStart)}
}

func (_c *MockWeeklyStatsStoreInterface_Get_Call) Run(run func(memberID string, weekStart string)) *MockWeeklyStatsStoreInterface_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockWeeklyStatsStoreInterface_Get_Call) Return(memberWeeklyStats *team.MemberWeeklyStats, err error) *MockWeeklyStatsStoreInterface_Get_Call {
	_c.Call.Return(memberWeeklyStats, err)
	return _c
}

func (_c *MockWeeklyStatsStoreInterface_Get_Call) RunAndReturn(run func(memberID string, weekStart string) (*team.MemberWeeklyStats, error)) *MockWeeklyStatsStoreInterface_Get_Call {
	_c.Call.Return(run)
	return _c
}

// GetAll provides a mock function for the type MockWeeklyStatsStoreInterface
func (_mock *MockWeeklyStatsStoreInterface) GetAll(weekStart string) (map[string]*team.MemberWeeklyStats, error) {
	ret := _mock.Called(weekStart)

	if len(ret) == 0 {
		panic("no return value specified for GetAll")
	}

	var r0 map[string]*team.MemberWeeklyStats
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (map[string]*team.MemberWeeklyStats, error)); ok {
		return returnFunc(weekStart)
	}
	if returnFunc, ok := ret.Get(0).(func(string) map[string]*team.MemberWeeklyStats); ok {
		r0 = returnFunc(weekStart)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[string]*team.MemberWeeklyStats)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(weekStart)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockWeeklyStatsStoreInterface_GetAll_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAll'
type MockWeeklyStatsStoreInterface_GetAll_Call struct {
	*mock.Call
}

// GetAll is a helper method to define mock.On call
//   - weekStart string
func (_e *MockWeeklyStatsStoreInterface_Expecter) GetAll(weekStart interface{}) *MockWeeklyStatsStoreInterface_GetAll_Call {
	return &MockWeeklyStatsStoreInterface_GetAll_Call{Call: _e.mock.On("GetAll", weekStart)}
}

func (_c *MockWeeklyStatsStoreInterface_GetAll_Call) Run(run func(weekStart string)) *MockWeeklyStatsStoreInterface_GetAll_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockWeeklyStatsStoreInterface_GetAll_Call) Return(stringToMemberWeeklyStats map[string]*team.MemberWeeklyStats, err error) *MockWeeklyStatsStoreInterface_GetAll_Call {
	_c.Call.Return(stringToMemberWeeklyStats, err)
	return _c
}

func (_c *MockWeeklyStatsStoreInterface_GetAll_Call) RunAndReturn(run func(weekStart string) (map[string]*team.MemberWeeklyStats, error)) *MockWeeklyStatsStoreInterface_GetAll_Call {
	_c.Call.Return(run)
	return _c
}

// GetExpiredMembers provides a mock function for the type MockWeeklyStatsStoreInterface
func (_mock *MockWeeklyStatsStoreInterface) GetExpiredMembers(memberIDs []string, weekStart string) []string {
	ret := _mock.Called(memberIDs, weekStart)

	if len(ret) == 0 {
		panic("no return value specified for GetExpiredMembers")
	}

	var r0 []string
	if returnFunc, ok := ret.Get(0).(func([]string, string) []string); ok {
		r0 = returnFunc(memberIDs, weekStart)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}
	return r0
}

// MockWeeklyStatsStoreInterface_GetExpiredMembers_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetExpiredMembers'
type MockWeeklyStatsStoreInterface_GetExpiredMembers_Call struct {
	*mock.Call
}

// GetExpiredMembers is a helper method to define mock.On call
//   - memberIDs []string
//   - weekStart string
func (_e *MockWeeklyStatsStoreInterface_Expecter) GetExpiredMembers(memberIDs interface{}, weekStart interface{}) *MockWeeklyStatsStoreInterface_GetExpiredMembers_Call {
	return &MockWeeklyStatsStoreInterface_GetExpiredMembers_Call{Call: _e.mock.On("GetExpiredMembers", memberIDs, weekStart)}
}

func (_c *MockWeeklyStatsStoreInterface_GetExpiredMembers_Call) Run(run func(memberIDs []string, weekStart string)) *MockWeeklyStatsStoreInterface_GetExpiredMembers_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 []string
		if args[0] != nil {
			arg0 = args[0].([]string)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockWeeklyStatsStoreInterface_GetExpiredMembers_Call) Return(strings []string) *MockWeeklyStatsStoreInterface_GetExpiredMembers_Call {
	_c.Call.Return(strings)
	return _c
}

func (_c *MockWeeklyStatsStoreInterface_GetExpiredMembers_Call) RunAndReturn(run func(memberIDs []string, weekStart string) []string) *MockWeeklyStatsStoreInterface_GetExpiredMembers_Call {
	_c.Call.Return(run)
	return _c
}

// Set provides a mock function for the type MockWeeklyStatsStoreInterface
func (_mock *MockWeeklyStatsStoreInterface) Set(memberID string, weekStart string, stats *team.MemberWeeklyStats) error {
	ret := _mock.Called(memberID, weekStart, stats)

	if len(ret) == 0 {
		panic("no return value specified for Set")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(string, string, *team.MemberWeeklyStats) error); ok {
		r0 = returnFunc(memberID, weekStart, stats)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockWeeklyStatsStoreInterface_Set_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Set'
type MockWeeklyStatsStoreInterface_Set_Call struct {
	*mock.Call
}

// Set is a helper method to define mock.On call
//   - memberID string
//   - weekStart string
//   - stats *team.MemberWeeklyStats
func (_e *MockWeeklyStatsStoreInterface_Expecter) Set(memberID interface{}, weekStart interface{}, stats interface{}) *MockWeeklyStatsStoreInterface_Set_Call {
	return &MockWeeklyStatsStoreInterface_Set_Call{Call: _e.mock.On("Set", memberID, weekStart, stats)}
}

func (_c *MockWeeklyStatsStoreInterface_Set_Call) Run(run func(memberID string, weekStart string, stats *team.MemberWeeklyStats)) *MockWeeklyStatsStoreInterface_Set_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 *team.MemberWeeklyStats
		if args[2] != nil {
			arg2 = args[2].(*team.MemberWeeklyStats)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockWeeklyStatsStoreInterface_Set_Call) Return(err error) *MockWeeklyStatsStoreInterface_Set_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockWeeklyStatsStoreInterface_Set_Call) RunAndReturn(run func(memberID string, weekStart string, stats *team.MemberWeeklyStats) error) *MockWeeklyStatsStoreInterface_Set_Call {
	_c.Call.Return(run)
	return _c
}

// SetWithExpiration provides a mock function for the type MockWeeklyStatsStoreInterface
func (_mock *MockWeeklyStatsStoreInterface) SetWithExpiration(memberID string, weekStart string, stats *team.MemberWeeklyStats, expiration time.Duration) error {
	ret := _mock.Called(memberID, weekStart, stats, expiration)

	if len(ret) == 0 {
		panic("no return value specified for SetWithExpiration")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(string, string, *team.MemberWeeklyStats, time.Duration) error); ok {
		r0 = returnFunc(memberID, weekStart, stats, expiration)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockWeeklyStatsStoreInterface_SetWithExpiration_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetWithExpiration'
type MockWeeklyStatsStoreInterface_SetWithExpiration_Call struct {
	*mock.Call
}

// SetWithExpiration is a helper method to define mock.On call
//   - memberID string
//   - weekStart string
//   - stats *team.MemberWeeklyStats
//   - expiration time.Duration
func (_e *MockWeeklyStatsStoreInterface_Expecter) SetWithExpiration(memberID interface{}, weekStart interface{}, stats interface{}, expiration interface{}) *MockWeeklyStatsStoreInterface_SetWithExpiration_Call {
	return &MockWeeklyStatsStoreInterface_SetWithExpiration_Call{Call: _e.mock.On("SetWithExpiration", memberID, weekStart, stats, expiration)}
}

func (_c *MockWeeklyStatsStoreInterface_SetWithExpiration_Call) Run(run func(memberID string, weekStart string, stats *team.MemberWeeklyStats, expiration time.Duration)) *MockWeeklyStatsStoreInterface_SetWithExpiration_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 *team.MemberWeeklyStats
		if args[2] != nil {
			arg2 = args[2].(*team.MemberWeeklyStats)
		}
		var arg3 time.Duration
		if args[3] != nil {
			arg3 = args[3].(time.Duration)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockWeeklyStatsStoreInterface_SetWithExpiration_Call) Return(err error) *MockWeeklyStatsStoreInterface_SetWithExpiration_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockWeeklyStatsStoreInterface_SetWithExpiration_Call) RunAndReturn(run func(memberID string, weekStart string, stats *team.MemberWeeklyStats, expiration time.Duration) error) *MockWeeklyStatsStoreInterface_SetWithExpiration_Call {
	_c.Call.Return(run)
	return _c
}
