// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"github.com/cocursor/backend/internal/domain/team"
	mock "github.com/stretchr/testify/mock"
)

// NewMockTeamServiceInterface creates a new instance of MockTeamServiceInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTeamServiceInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTeamServiceInterface {
	mock := &MockTeamServiceInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockTeamServiceInterface is an autogenerated mock type for the TeamServiceInterface type
type MockTeamServiceInterface struct {
	mock.Mock
}

type MockTeamServiceInterface_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTeamServiceInterface) EXPECT() *MockTeamServiceInterface_Expecter {
	return &MockTeamServiceInterface_Expecter{mock: &_m.Mock}
}

// GetOnlineMembers provides a mock function for the type MockTeamServiceInterface
func (_mock *MockTeamServiceInterface) GetOnlineMembers(teamID string) ([]*team.TeamMember, error) {
	ret := _mock.Called(teamID)

	if len(ret) == 0 {
		panic("no return value specified for GetOnlineMembers")
	}

	var r0 []*team.TeamMember
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) ([]*team.TeamMember, error)); ok {
		return returnFunc(teamID)
	}
	if returnFunc, ok := ret.Get(0).(func(string) []*team.TeamMember); ok {
		r0 = returnFunc(teamID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*team.TeamMember)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(teamID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTeamServiceInterface_GetOnlineMembers_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetOnlineMembers'
type MockTeamServiceInterface_GetOnlineMembers_Call struct {
	*mock.Call
}

// GetOnlineMembers is a helper method to define mock.On call
//   - teamID string
func (_e *MockTeamServiceInterface_Expecter) GetOnlineMembers(teamID interface{}) *MockTeamServiceInterface_GetOnlineMembers_Call {
	return &MockTeamServiceInterface_GetOnlineMembers_Call{Call: _e.mock.On("GetOnlineMembers", teamID)}
}

func (_c *MockTeamServiceInterface_GetOnlineMembers_Call) Run(run func(teamID string)) *MockTeamServiceInterface_GetOnlineMembers_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockTeamServiceInterface_GetOnlineMembers_Call) Return(teamMembers []*team.TeamMember, err error) *MockTeamServiceInterface_GetOnlineMembers_Call {
	_c.Call.Return(teamMembers, err)
	return _c
}

func (_c *MockTeamServiceInterface_GetOnlineMembers_Call) RunAndReturn(run func(teamID string) ([]*team.TeamMember, error)) *MockTeamServiceInterface_GetOnlineMembers_Call {
	_c.Call.Return(run)
	return _c
}

// GetSkillIndex provides a mock function for the type MockTeamServiceInterface
func (_mock *MockTeamServiceInterface) GetSkillIndex(teamID string) (*team.TeamSkillIndex, error) {
	ret := _mock.Called(teamID)

	if len(ret) == 0 {
		panic("no return value specified for GetSkillIndex")
	}

	var r0 *team.TeamSkillIndex
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (*team.TeamSkillIndex, error)); ok {
		return returnFunc(teamID)
	}
	if returnFunc, ok := ret.Get(0).(func(string) *team.TeamSkillIndex); ok {
		r0 = returnFunc(teamID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*team.TeamSkillIndex)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(teamID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTeamServiceInterface_GetSkillIndex_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetSkillIndex'
type MockTeamServiceInterface_GetSkillIndex_Call struct {
	*mock.Call
}

// GetSkillIndex is a helper method to define mock.On call
//   - teamID string
func (_e *MockTeamServiceInterface_Expecter) GetSkillIndex(teamID interface{}) *MockTeamServiceInterface_GetSkillIndex_Call {
	return &MockTeamServiceInterface_GetSkillIndex_Call{Call: _e.mock.On("GetSkillIndex", teamID)}
}

func (_c *MockTeamServiceInterface_GetSkillIndex_Call) Run(run func(teamID string)) *MockTeamServiceInterface_GetSkillIndex_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockTeamServiceInterface_GetSkillIndex_Call) Return(teamSkillIndex *team.TeamSkillIndex, err error) *MockTeamServiceInterface_GetSkillIndex_Call {
	_c.Call.Return(teamSkillIndex, err)
	return _c
}

func (_c *MockTeamServiceInterface_GetSkillIndex_Call) RunAndReturn(run func(teamID string) (*team.TeamSkillIndex, error)) *MockTeamServiceInterface_GetSkillIndex_Call {
	_c.Call.Return(run)
	return _c
}

// GetTeam provides a mock function for the type MockTeamServiceInterface
func (_mock *MockTeamServiceInterface) GetTeam(teamID string) (*team.Team, error) {
	ret := _mock.Called(teamID)

	if len(ret) == 0 {
		panic("no return value specified for GetTeam")
	}

	var r0 *team.Team
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (*team.Team, error)); ok {
		return returnFunc(teamID)
	}
	if returnFunc, ok := ret.Get(0).(func(string) *team.Team); ok {
		r0 = returnFunc(teamID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*team.Team)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(teamID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTeamServiceInterface_GetTeam_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetTeam'
type MockTeamServiceInterface_GetTeam_Call struct {
	*mock.Call
}

// GetTeam is a helper method to define mock.On call
//   - teamID string
func (_e *MockTeamServiceInterface_Expecter) GetTeam(teamID interface{}) *MockTeamServiceInterface_GetTeam_Call {
	return &MockTeamServiceInterface_GetTeam_Call{Call: _e.mock.On("GetTeam", teamID)}
}

func (_c *MockTeamServiceInterface_GetTeam_Call) Run(run func(teamID string)) *MockTeamServiceInterface_GetTeam_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockTeamServiceInterface_GetTeam_Call) Return(team1 *team.Team, err error) *MockTeamServiceInterface_GetTeam_Call {
	_c.Call.Return(team1, err)
	return _c
}

func (_c *MockTeamServiceInterface_GetTeam_Call) RunAndReturn(run func(teamID string) (*team.Team, error)) *MockTeamServiceInterface_GetTeam_Call {
	_c.Call.Return(run)
	return _c
}

// GetTeamList provides a mock function for the type MockTeamServiceInterface
func (_mock *MockTeamServiceInterface) GetTeamList() []*team.Team {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetTeamList")
	}

	var r0 []*team.Team
	if returnFunc, ok := ret.Get(0).(func() []*team.Team); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*team.Team)
		}
	}
	return r0
}

// MockTeamServiceInterface_GetTeamList_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetTeamList'
type MockTeamServiceInterface_GetTeamList_Call struct {
	*mock.Call
}

// GetTeamList is a helper method to define mock.On call
func (_e *MockTeamServiceInterface_Expecter) GetTeamList() *MockTeamServiceInterface_GetTeamList_Call {
	return &MockTeamServiceInterface_GetTeamList_Call{Call: _e.mock.On("GetTeamList")}
}

func (_c *MockTeamServiceInterface_GetTeamList_Call) Run(run func()) *MockTeamServiceInterface_GetTeamList_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockTeamServiceInterface_GetTeamList_Call) Return(teams []*team.Team) *MockTeamServiceInterface_GetTeamList_Call {
	_c.Call.Return(teams)
	return _c
}

func (_c *MockTeamServiceInterface_GetTeamList_Call) RunAndReturn(run func() []*team.Team) *MockTeamServiceInterface_GetTeamList_Call {
	_c.Call.Return(run)
	return _c
}

// GetTeamMembers provides a mock function for the type MockTeamServiceInterface
func (_mock *MockTeamServiceInterface) GetTeamMembers(teamID string) ([]*team.TeamMember, error) {
	ret := _mock.Called(teamID)

	if len(ret) == 0 {
		panic("no return value specified for GetTeamMembers")
	}

	var r0 []*team.TeamMember
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) ([]*team.TeamMember, error)); ok {
		return returnFunc(teamID)
	}
	if returnFunc, ok := ret.Get(0).(func(string) []*team.TeamMember); ok {
		r0 = returnFunc(teamID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*team.TeamMember)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(teamID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTeamServiceInterface_GetTeamMembers_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetTeamMembers'
type MockTeamServiceInterface_GetTeamMembers_Call struct {
	*mock.Call
}

// GetTeamMembers is a helper method to define mock.On call
//   - teamID string
func (_e *MockTeamServiceInterface_Expecter) GetTeamMembers(teamID interface{}) *MockTeamServiceInterface_GetTeamMembers_Call {
	return &MockTeamServiceInterface_GetTeamMembers_Call{Call: _e.mock.On("GetTeamMembers", teamID)}
}

func (_c *MockTeamServiceInterface_GetTeamMembers_Call) Run(run func(teamID string)) *MockTeamServiceInterface_GetTeamMembers_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockTeamServiceInterface_GetTeamMembers_Call) Return(teamMembers []*team.TeamMember, err error) *MockTeamServiceInterface_GetTeamMembers_Call {
	_c.Call.Return(teamMembers, err)
	return _c
}

func (_c *MockTeamServiceInterface_GetTeamMembers_Call) RunAndReturn(run func(teamID string) ([]*team.TeamMember, error)) *MockTeamServiceInterface_GetTeamMembers_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateLastSync provides a mock function for the type MockTeamServiceInterface
func (_mock *MockTeamServiceInterface) UpdateLastSync(teamID string) {
	_mock.Called(teamID)
	return
}

// MockTeamServiceInterface_UpdateLastSync_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateLastSync'
type MockTeamServiceInterface_UpdateLastSync_Call struct {
	*mock.Call
}

// UpdateLastSync is a helper method to define mock.On call
//   - teamID string
func (_e *MockTeamServiceInterface_Expecter) UpdateLastSync(teamID interface{}) *MockTeamServiceInterface_UpdateLastSync_Call {
	return &MockTeamServiceInterface_UpdateLastSync_Call{Call: _e.mock.On("UpdateLastSync", teamID)}
}

func (_c *MockTeamServiceInterface_UpdateLastSync_Call) Run(run func(teamID string)) *MockTeamServiceInterface_UpdateLastSync_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockTeamServiceInterface_UpdateLastSync_Call) Return() *MockTeamServiceInterface_UpdateLastSync_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockTeamServiceInterface_UpdateLastSync_Call) RunAndReturn(run func(teamID string)) *MockTeamServiceInterface_UpdateLastSync_Call {
	_c.Run(run)
	return _c
}

// UpdateLeaderOnline provides a mock function for the type MockTeamServiceInterface
func (_mock *MockTeamServiceInterface) UpdateLeaderOnline(teamID string, online bool) {
	_mock.Called(teamID, online)
	return
}

// MockTeamServiceInterface_UpdateLeaderOnline_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateLeaderOnline'
type MockTeamServiceInterface_UpdateLeaderOnline_Call struct {
	*mock.Call
}

// UpdateLeaderOnline is a helper method to define mock.On call
//   - teamID string
//   - online bool
func (_e *MockTeamServiceInterface_Expecter) UpdateLeaderOnline(teamID interface{}, online interface{}) *MockTeamServiceInterface_UpdateLeaderOnline_Call {
	return &MockTeamServiceInterface_UpdateLeaderOnline_Call{Call: _e.mock.On("UpdateLeaderOnline", teamID, online)}
}

func (_c *MockTeamServiceInterface_UpdateLeaderOnline_Call) Run(run func(teamID string, online bool)) *MockTeamServiceInterface_UpdateLeaderOnline_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 bool
		if args[1] != nil {
			arg1 = args[1].(bool)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockTeamServiceInterface_UpdateLeaderOnline_Call) Return() *MockTeamServiceInterface_UpdateLeaderOnline_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockTeamServiceInterface_UpdateLeaderOnline_Call) RunAndReturn(run func(teamID string, online bool)) *MockTeamServiceInterface_UpdateLeaderOnline_Call {
	_c.Run(run)
	return _c
}
