// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"net/http"
	"time"

	"github.com/cocursor/backend/internal/domain/team"
	mock "github.com/stretchr/testify/mock"
)

// NewMockTeamServiceInterface creates a new instance of MockTeamServiceInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTeamServiceInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTeamServiceInterface {
	mock := &MockTeamServiceInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockTeamServiceInterface is an autogenerated mock type for the TeamServiceInterface type
type MockTeamServiceInterface struct {
	mock.Mock
}

type MockTeamServiceInterface_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTeamServiceInterface) EXPECT() *MockTeamServiceInterface_Expecter {
	return &MockTeamServiceInterface_Expecter{mock: &_m.Mock}
}

// GetOnlineMembers provides a mock function for the type MockTeamServiceInterface
func (_mock *MockTeamServiceInterface) GetOnlineMembers(teamID string) ([]*team.TeamMember, error) {
	ret := _mock.Called(teamID)

	if len(ret) == 0 {
		panic("no return value specified for GetOnlineMembers")
	}

	var r0 []*team.TeamMember
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) ([]*team.TeamMember, error)); ok {
		return returnFunc(teamID)
	}
	if returnFunc, ok := ret.Get(0).(func(string) []*team.TeamMember); ok {
		r0 = returnFunc(teamID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*team.TeamMember)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(teamID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTeamServiceInterface_GetOnlineMembers_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetOnlineMembers'
type MockTeamServiceInterface_GetOnlineMembers_Call struct {
	*mock.Call
}

// GetOnlineMembers is a helper method to define mock.On call
//   - teamID string
func (_e *MockTeamServiceInterface_Expecter) GetOnlineMembers(teamID interface{}) *MockTeamServiceInterface_GetOnlineMembers_Call {
	return &MockTeamServiceInterface_GetOnlineMembers_Call{Call: _e.mock.On("GetOnlineMembers", teamID)}
}

func (_c *MockTeamServiceInterface_GetOnlineMembers_Call) Run(run func(teamID string)) *MockTeamServiceInterface_GetOnlineMembers_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockTeamServiceInterface_GetOnlineMembers_Call) Return(teamMembers []*team.TeamMember, err error) *MockTeamServiceInterface_GetOnlineMembers_Call {
	_c.Call.Return(teamMembers, err)
	return _c
}

func (_c *MockTeamServiceInterface_GetOnlineMembers_Call) RunAndReturn(run func(teamID string) ([]*team.TeamMember, error)) *MockTeamServiceInterface_GetOnlineMembers_Call {
	_c.Call.Return(run)
	return _c
}

// GetTeam provides a mock function for the type MockTeamServiceInterface
func (_mock *MockTeamServiceInterface) GetTeam(teamID string) (*team.Team, error) {
	ret := _mock.Called(teamID)

	if len(ret) == 0 {
		panic("no return value specified for GetTeam")
	}

	var r0 *team.Team
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (*team.Team, error)); ok {
		return returnFunc(teamID)
	}
	if returnFunc, ok := ret.Get(0).(func(string) *team.Team); ok {
		r0 = returnFunc(teamID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*team.Team)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(teamID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTeamServiceInterface_GetTeam_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetTeam'
type MockTeamServiceInterface_GetTeam_Call struct {
	*mock.Call
}

// GetTeam is a helper method to define mock.On call
//   - teamID string
func (_e *MockTeamServiceInterface_Expecter) GetTeam(teamID interface{}) *MockTeamServiceInterface_GetTeam_Call {
	return &MockTeamServiceInterface_GetTeam_Call{Call: _e.mock.On("GetTeam", teamID)}
}

func (_c *MockTeamServiceInterface_GetTeam_Call) Run(run func(teamID string)) *MockTeamServiceInterface_GetTeam_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockTeamServiceInterface_GetTeam_Call) Return(team1 *team.Team, err error) *MockTeamServiceInterface_GetTeam_Call {
	_c.Call.Return(team1, err)
	return _c
}

func (_c *MockTeamServiceInterface_GetTeam_Call) RunAndReturn(run func(teamID string) (*team.Team, error)) *MockTeamServiceInterface_GetTeam_Call {
	_c.Call.Return(run)
	return _c
}

// GetTeamMembers provides a mock function for the type MockTeamServiceInterface
func (_mock *MockTeamServiceInterface) GetTeamMembers(teamID string) ([]*team.TeamMember, error) {
	ret := _mock.Called(teamID)

	if len(ret) == 0 {
		panic("no return value specified for GetTeamMembers")
	}

	var r0 []*team.TeamMember
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) ([]*team.TeamMember, error)); ok {
		return returnFunc(teamID)
	}
	if returnFunc, ok := ret.Get(0).(func(string) []*team.TeamMember); ok {
		r0 = returnFunc(teamID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*team.TeamMember)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(teamID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTeamServiceInterface_GetTeamMembers_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetTeamMembers'
type MockTeamServiceInterface_GetTeamMembers_Call struct {
	*mock.Call
}

// GetTeamMembers is a helper method to define mock.On call
//   - teamID string
func (_e *MockTeamServiceInterface_Expecter) GetTeamMembers(teamID interface{}) *MockTeamServiceInterface_GetTeamMembers_Call {
	return &MockTeamServiceInterface_GetTeamMembers_Call{Call: _e.mock.On("GetTeamMembers", teamID)}
}

func (_c *MockTeamServiceInterface_GetTeamMembers_Call) Run(run func(teamID string)) *MockTeamServiceInterface_GetTeamMembers_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockTeamServiceInterface_GetTeamMembers_Call) Return(teamMembers []*team.TeamMember, err error) *MockTeamServiceInterface_GetTeamMembers_Call {
	_c.Call.Return(teamMembers, err)
	return _c
}

func (_c *MockTeamServiceInterface_GetTeamMembers_Call) RunAndReturn(run func(teamID string) ([]*team.TeamMember, error)) *MockTeamServiceInterface_GetTeamMembers_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockProjectConfigStoreInterface creates a new instance of MockProjectConfigStoreInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockProjectConfigStoreInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockProjectConfigStoreInterface {
	mock := &MockProjectConfigStoreInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockProjectConfigStoreInterface is an autogenerated mock type for the ProjectConfigStoreInterface type
type MockProjectConfigStoreInterface struct {
	mock.Mock
}

type MockProjectConfigStoreInterface_Expecter struct {
	mock *mock.Mock
}

func (_m *MockProjectConfigStoreInterface) EXPECT() *MockProjectConfigStoreInterface_Expecter {
	return &MockProjectConfigStoreInterface_Expecter{mock: &_m.Mock}
}

// AddProject provides a mock function for the type MockProjectConfigStoreInterface
func (_mock *MockProjectConfigStoreInterface) AddProject(project team.ProjectMatcher) error {
	ret := _mock.Called(project)

	if len(ret) == 0 {
		panic("no return value specified for AddProject")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(team.ProjectMatcher) error); ok {
		r0 = returnFunc(project)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockProjectConfigStoreInterface_AddProject_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddProject'
type MockProjectConfigStoreInterface_AddProject_Call struct {
	*mock.Call
}

// AddProject is a helper method to define mock.On call
//   - project team.ProjectMatcher
func (_e *MockProjectConfigStoreInterface_Expecter) AddProject(project interface{}) *MockProjectConfigStoreInterface_AddProject_Call {
	return &MockProjectConfigStoreInterface_AddProject_Call{Call: _e.mock.On("AddProject", project)}
}

func (_c *MockProjectConfigStoreInterface_AddProject_Call) Run(run func(project team.ProjectMatcher)) *MockProjectConfigStoreInterface_AddProject_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 team.ProjectMatcher
		if args[0] != nil {
			arg0 = args[0].(team.ProjectMatcher)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockProjectConfigStoreInterface_AddProject_Call) Return(err error) *MockProjectConfigStoreInterface_AddProject_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockProjectConfigStoreInterface_AddProject_Call) RunAndReturn(run func(project team.ProjectMatcher) error) *MockProjectConfigStoreInterface_AddProject_Call {
	_c.Call.Return(run)
	return _c
}

// GetRepoURLs provides a mock function for the type MockProjectConfigStoreInterface
func (_mock *MockProjectConfigStoreInterface) GetRepoURLs() []string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetRepoURLs")
	}

	var r0 []string
	if returnFunc, ok := ret.Get(0).(func() []string); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}
	return r0
}

// MockProjectConfigStoreInterface_GetRepoURLs_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetRepoURLs'
type MockProjectConfigStoreInterface_GetRepoURLs_Call struct {
	*mock.Call
}

// GetRepoURLs is a helper method to define mock.On call
func (_e *MockProjectConfigStoreInterface_Expecter) GetRepoURLs() *MockProjectConfigStoreInterface_GetRepoURLs_Call {
	return &MockProjectConfigStoreInterface_GetRepoURLs_Call{Call: _e.mock.On("GetRepoURLs")}
}

func (_c *MockProjectConfigStoreInterface_GetRepoURLs_Call) Run(run func()) *MockProjectConfigStoreInterface_GetRepoURLs_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockProjectConfigStoreInterface_GetRepoURLs_Call) Return(strings []string) *MockProjectConfigStoreInterface_GetRepoURLs_Call {
	_c.Call.Return(strings)
	return _c
}

func (_c *MockProjectConfigStoreInterface_GetRepoURLs_Call) RunAndReturn(run func() []string) *MockProjectConfigStoreInterface_GetRepoURLs_Call {
	_c.Call.Return(run)
	return _c
}

// Load provides a mock function for the type MockProjectConfigStoreInterface
func (_mock *MockProjectConfigStoreInterface) Load() (*team.TeamProjectConfig, error) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Load")
	}

	var r0 *team.TeamProjectConfig
	var r1 error
	if returnFunc, ok := ret.Get(0).(func() (*team.TeamProjectConfig, error)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() *team.TeamProjectConfig); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*team.TeamProjectConfig)
		}
	}
	if returnFunc, ok := ret.Get(1).(func() error); ok {
		r1 = returnFunc()
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockProjectConfigStoreInterface_Load_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Load'
type MockProjectConfigStoreInterface_Load_Call struct {
	*mock.Call
}

// Load is a helper method to define mock.On call
func (_e *MockProjectConfigStoreInterface_Expecter) Load() *MockProjectConfigStoreInterface_Load_Call {
	return &MockProjectConfigStoreInterface_Load_Call{Call: _e.mock.On("Load")}
}

func (_c *MockProjectConfigStoreInterface_Load_Call) Run(run func()) *MockProjectConfigStoreInterface_Load_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockProjectConfigStoreInterface_Load_Call) Return(teamProjectConfig *team.TeamProjectConfig, err error) *MockProjectConfigStoreInterface_Load_Call {
	_c.Call.Return(teamProjectConfig, err)
	return _c
}

func (_c *MockProjectConfigStoreInterface_Load_Call) RunAndReturn(run func() (*team.TeamProjectConfig, error)) *MockProjectConfigStoreInterface_Load_Call {
	_c.Call.Return(run)
	return _c
}

// RemoveProject provides a mock function for the type MockProjectConfigStoreInterface
func (_mock *MockProjectConfigStoreInterface) RemoveProject(projectID string) error {
	ret := _mock.Called(projectID)

	if len(ret) == 0 {
		panic("no return value specified for RemoveProject")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(string) error); ok {
		r0 = returnFunc(projectID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockProjectConfigStoreInterface_RemoveProject_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RemoveProject'
type MockProjectConfigStoreInterface_RemoveProject_Call struct {
	*mock.Call
}

// RemoveProject is a helper method to define mock.On call
//   - projectID string
func (_e *MockProjectConfigStoreInterface_Expecter) RemoveProject(projectID interface{}) *MockProjectConfigStoreInterface_RemoveProject_Call {
	return &MockProjectConfigStoreInterface_RemoveProject_Call{Call: _e.mock.On("RemoveProject", projectID)}
}

func (_c *MockProjectConfigStoreInterface_RemoveProject_Call) Run(run func(projectID string)) *MockProjectConfigStoreInterface_RemoveProject_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockProjectConfigStoreInterface_RemoveProject_Call) Return(err error) *MockProjectConfigStoreInterface_RemoveProject_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockProjectConfigStoreInterface_RemoveProject_Call) RunAndReturn(run func(projectID string) error) *MockProjectConfigStoreInterface_RemoveProject_Call {
	_c.Call.Return(run)
	return _c
}

// Save provides a mock function for the type MockProjectConfigStoreInterface
func (_mock *MockProjectConfigStoreInterface) Save(config *team.TeamProjectConfig) error {
	ret := _mock.Called(config)

	if len(ret) == 0 {
		panic("no return value specified for Save")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(*team.TeamProjectConfig) error); ok {
		r0 = returnFunc(config)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockProjectConfigStoreInterface_Save_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Save'
type MockProjectConfigStoreInterface_Save_Call struct {
	*mock.Call
}

// Save is a helper method to define mock.On call
//   - config *team.TeamProjectConfig
func (_e *MockProjectConfigStoreInterface_Expecter) Save(config interface{}) *MockProjectConfigStoreInterface_Save_Call {
	return &MockProjectConfigStoreInterface_Save_Call{Call: _e.mock.On("Save", config)}
}

func (_c *MockProjectConfigStoreInterface_Save_Call) Run(run func(config *team.TeamProjectConfig)) *MockProjectConfigStoreInterface_Save_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *team.TeamProjectConfig
		if args[0] != nil {
			arg0 = args[0].(*team.TeamProjectConfig)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockProjectConfigStoreInterface_Save_Call) Return(err error) *MockProjectConfigStoreInterface_Save_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockProjectConfigStoreInterface_Save_Call) RunAndReturn(run func(config *team.TeamProjectConfig) error) *MockProjectConfigStoreInterface_Save_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateProject provides a mock function for the type MockProjectConfigStoreInterface
func (_mock *MockProjectConfigStoreInterface) UpdateProject(project team.ProjectMatcher) error {
	ret := _mock.Called(project)

	if len(ret) == 0 {
		panic("no return value specified for UpdateProject")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(team.ProjectMatcher) error); ok {
		r0 = returnFunc(project)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockProjectConfigStoreInterface_UpdateProject_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateProject'
type MockProjectConfigStoreInterface_UpdateProject_Call struct {
	*mock.Call
}

// UpdateProject is a helper method to define mock.On call
//   - project team.ProjectMatcher
func (_e *MockProjectConfigStoreInterface_Expecter) UpdateProject(project interface{}) *MockProjectConfigStoreInterface_UpdateProject_Call {
	return &MockProjectConfigStoreInterface_UpdateProject_Call{Call: _e.mock.On("UpdateProject", project)}
}

func (_c *MockProjectConfigStoreInterface_UpdateProject_Call) Run(run func(project team.ProjectMatcher)) *MockProjectConfigStoreInterface_UpdateProject_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 team.ProjectMatcher
		if args[0] != nil {
			arg0 = args[0].(team.ProjectMatcher)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockProjectConfigStoreInterface_UpdateProject_Call) Return(err error) *MockProjectConfigStoreInterface_UpdateProject_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockProjectConfigStoreInterface_UpdateProject_Call) RunAndReturn(run func(project team.ProjectMatcher) error) *MockProjectConfigStoreInterface_UpdateProject_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockWeeklyStatsStoreInterface creates a new instance of MockWeeklyStatsStoreInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockWeeklyStatsStoreInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockWeeklyStatsStoreInterface {
	mock := &MockWeeklyStatsStoreInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockWeeklyStatsStoreInterface is an autogenerated mock type for the WeeklyStatsStoreInterface type
type MockWeeklyStatsStoreInterface struct {
	mock.Mock
}

type MockWeeklyStatsStoreInterface_Expecter struct {
	mock *mock.Mock
}

func (_m *MockWeeklyStatsStoreInterface) EXPECT() *MockWeeklyStatsStoreInterface_Expecter {
	return &MockWeeklyStatsStoreInterface_Expecter{mock: &_m.Mock}
}

// Clear provides a mock function for the type MockWeeklyStatsStoreInterface
func (_mock *MockWeeklyStatsStoreInterface) Clear() error {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Clear")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func() error); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockWeeklyStatsStoreInterface_Clear_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Clear'
type MockWeeklyStatsStoreInterface_Clear_Call struct {
	*mock.Call
}

// Clear is a helper method to define mock.On call
func (_e *MockWeeklyStatsStoreInterface_Expecter) Clear() *MockWeeklyStatsStoreInterface_Clear_Call {
	return &MockWeeklyStatsStoreInterface_Clear_Call{Call: _e.mock.On("Clear")}
}

func (_c *MockWeeklyStatsStoreInterface_Clear_Call) Run(run func()) *MockWeeklyStatsStoreInterface_Clear_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockWeeklyStatsStoreInterface_Clear_Call) Return(err error) *MockWeeklyStatsStoreInterface_Clear_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockWeeklyStatsStoreInterface_Clear_Call) RunAndReturn(run func() error) *MockWeeklyStatsStoreInterface_Clear_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function for the type MockWeeklyStatsStoreInterface
func (_mock *MockWeeklyStatsStoreInterface) Delete(memberID string, weekStart string) error {
	ret := _mock.Called(memberID, weekStart)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(string, string) error); ok {
		r0 = returnFunc(memberID, weekStart)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockWeeklyStatsStoreInterface_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockWeeklyStatsStoreInterface_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - memberID string
//   - weekStart string
func (_e *MockWeeklyStatsStoreInterface_Expecter) Delete(memberID interface{}, weekStart interface{}) *MockWeeklyStatsStoreInterface_Delete_Call {
	return &MockWeeklyStatsStoreInterface_Delete_Call{Call: _e.mock.On("Delete", memberID, weekStart)}
}

func (_c *MockWeeklyStatsStoreInterface_Delete_Call) Run(run func(memberID string, weekStart string)) *MockWeeklyStatsStoreInterface_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockWeeklyStatsStoreInterface_Delete_Call) Return(err error) *MockWeeklyStatsStoreInterface_Delete_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockWeeklyStatsStoreInterface_Delete_Call) RunAndReturn(run func(memberID string, weekStart string) error) *MockWeeklyStatsStoreInterface_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// Get provides a mock function for the type MockWeeklyStatsStoreInterface
func (_mock *MockWeeklyStatsStoreInterface) Get(memberID string, weekStart string) (*team.MemberWeeklyStats, error) {
	ret := _mock.Called(memberID, weekStart)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 *team.MemberWeeklyStats
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string, string) (*team.MemberWeeklyStats, error)); ok {
		return returnFunc(memberID, weekStart)
	}
	if returnFunc, ok := ret.Get(0).(func(string, string) *team.MemberWeeklyStats); ok {
		r0 = returnFunc(memberID, weekStart)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*team.MemberWeeklyStats)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string, string) error); ok {
		r1 = returnFunc(memberID, weekStart)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockWeeklyStatsStoreInterface_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type MockWeeklyStatsStoreInterface_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - memberID string
//   - weekStart string
func (_e *MockWeeklyStatsStoreInterface_Expecter) Get(memberID interface{}, weekStart interface{}) *MockWeeklyStatsStoreInterface_Get_Call {
	return &MockWeeklyStatsStoreInterface_Get_Call{Call: _e.mock.On("Get", memberID, weekStart)}
}

func (_c *MockWeeklyStatsStoreInterface_Get_Call) Run(run func(memberID string, weekStart string)) *MockWeeklyStatsStoreInterface_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockWeeklyStatsStoreInterface_Get_Call) Return(memberWeeklyStats *team.MemberWeeklyStats, err error) *MockWeeklyStatsStoreInterface_Get_Call {
	_c.Call.Return(memberWeeklyStats, err)
	return _c
}

func (_c *MockWeeklyStatsStoreInterface_Get_Call) RunAndReturn(run func(memberID string, weekStart string) (*team.MemberWeeklyStats, error)) *MockWeeklyStatsStoreInterface_Get_Call {
	_c.Call.Return(run)
	return _c
}

// GetAll provides a mock function for the type MockWeeklyStatsStoreInterface
func (_mock *MockWeeklyStatsStoreInterface) GetAll(weekStart string) (map[string]*team.MemberWeeklyStats, error) {
	ret := _mock.Called(weekStart)

	if len(ret) == 0 {
		panic("no return value specified for GetAll")
	}

	var r0 map[string]*team.MemberWeeklyStats
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (map[string]*team.MemberWeeklyStats, error)); ok {
		return returnFunc(weekStart)
	}
	if returnFunc, ok := ret.Get(0).(func(string) map[string]*team.MemberWeeklyStats); ok {
		r0 = returnFunc(weekStart)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[string]*team.MemberWeeklyStats)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(weekStart)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockWeeklyStatsStoreInterface_GetAll_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAll'
type MockWeeklyStatsStoreInterface_GetAll_Call struct {
	*mock.Call
}

// GetAll is a helper method to define mock.On call
//   - weekStart string
func (_e *MockWeeklyStatsStoreInterface_Expecter) GetAll(weekStart interface{}) *MockWeeklyStatsStoreInterface_GetAll_Call {
	return &MockWeeklyStatsStoreInterface_GetAll_Call{Call: _e.mock.On("GetAll", weekStart)}
}

func (_c *MockWeeklyStatsStoreInterface_GetAll_Call) Run(run func(weekStart string)) *MockWeeklyStatsStoreInterface_GetAll_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockWeeklyStatsStoreInterface_GetAll_Call) Return(stringToMemberWeeklyStats map[string]*team.MemberWeeklyStats, err error) *MockWeeklyStatsStoreInterface_GetAll_Call {
	_c.Call.Return(stringToMemberWeeklyStats, err)
	return _c
}

func (_c *MockWeeklyStatsStoreInterface_GetAll_Call) RunAndReturn(run func(weekStart string) (map[string]*team.MemberWeeklyStats, error)) *MockWeeklyStatsStoreInterface_GetAll_Call {
	_c.Call.Return(run)
	return _c
}

// GetExpiredMembers provides a mock function for the type MockWeeklyStatsStoreInterface
func (_mock *MockWeeklyStatsStoreInterface) GetExpiredMembers(memberIDs []string, weekStart string) []string {
	ret := _mock.Called(memberIDs, weekStart)

	if len(ret) == 0 {
		panic("no return value specified for GetExpiredMembers")
	}

	var r0 []string
	if returnFunc, ok := ret.Get(0).(func([]string, string) []string); ok {
		r0 = returnFunc(memberIDs, weekStart)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}
	return r0
}

// MockWeeklyStatsStoreInterface_GetExpiredMembers_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetExpiredMembers'
type MockWeeklyStatsStoreInterface_GetExpiredMembers_Call struct {
	*mock.Call
}

// GetExpiredMembers is a helper method to define mock.On call
//   - memberIDs []string
//   - weekStart string
func (_e *MockWeeklyStatsStoreInterface_Expecter) GetExpiredMembers(memberIDs interface{}, weekStart interface{}) *MockWeeklyStatsStoreInterface_GetExpiredMembers_Call {
	return &MockWeeklyStatsStoreInterface_GetExpiredMembers_Call{Call: _e.mock.On("GetExpiredMembers", memberIDs, weekStart)}
}

func (_c *MockWeeklyStatsStoreInterface_GetExpiredMembers_Call) Run(run func(memberIDs []string, weekStart string)) *MockWeeklyStatsStoreInterface_GetExpiredMembers_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 []string
		if args[0] != nil {
			arg0 = args[0].([]string)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockWeeklyStatsStoreInterface_GetExpiredMembers_Call) Return(strings []string) *MockWeeklyStatsStoreInterface_GetExpiredMembers_Call {
	_c.Call.Return(strings)
	return _c
}

func (_c *MockWeeklyStatsStoreInterface_GetExpiredMembers_Call) RunAndReturn(run func(memberIDs []string, weekStart string) []string) *MockWeeklyStatsStoreInterface_GetExpiredMembers_Call {
	_c.Call.Return(run)
	return _c
}

// Set provides a mock function for the type MockWeeklyStatsStoreInterface
func (_mock *MockWeeklyStatsStoreInterface) Set(memberID string, weekStart string, stats *team.MemberWeeklyStats) error {
	ret := _mock.Called(memberID, weekStart, stats)

	if len(ret) == 0 {
		panic("no return value specified for Set")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(string, string, *team.MemberWeeklyStats) error); ok {
		r0 = returnFunc(memberID, weekStart, stats)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockWeeklyStatsStoreInterface_Set_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Set'
type MockWeeklyStatsStoreInterface_Set_Call struct {
	*mock.Call
}

// Set is a helper method to define mock.On call
//   - memberID string
//   - weekStart string
//   - stats *team.MemberWeeklyStats
func (_e *MockWeeklyStatsStoreInterface_Expecter) Set(memberID interface{}, weekStart interface{}, stats interface{}) *MockWeeklyStatsStoreInterface_Set_Call {
	return &MockWeeklyStatsStoreInterface_Set_Call{Call: _e.mock.On("Set", memberID, weekStart, stats)}
}

func (_c *MockWeeklyStatsStoreInterface_Set_Call) Run(run func(memberID string, weekStart string, stats *team.MemberWeeklyStats)) *MockWeeklyStatsStoreInterface_Set_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 *team.MemberWeeklyStats
		if args[2] != nil {
			arg2 = args[2].(*team.MemberWeeklyStats)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockWeeklyStatsStoreInterface_Set_Call) Return(err error) *MockWeeklyStatsStoreInterface_Set_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockWeeklyStatsStoreInterface_Set_Call) RunAndReturn(run func(memberID string, weekStart string, stats *team.MemberWeeklyStats) error) *MockWeeklyStatsStoreInterface_Set_Call {
	_c.Call.Return(run)
	return _c
}

// SetWithExpiration provides a mock function for the type MockWeeklyStatsStoreInterface
func (_mock *MockWeeklyStatsStoreInterface) SetWithExpiration(memberID string, weekStart string, stats *team.MemberWeeklyStats, expiration time.Duration) error {
	ret := _mock.Called(memberID, weekStart, stats, expiration)

	if len(ret) == 0 {
		panic("no return value specified for SetWithExpiration")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(string, string, *team.MemberWeeklyStats, time.Duration) error); ok {
		r0 = returnFunc(memberID, weekStart, stats, expiration)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockWeeklyStatsStoreInterface_SetWithExpiration_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetWithExpiration'
type MockWeeklyStatsStoreInterface_SetWithExpiration_Call struct {
	*mock.Call
}

// SetWithExpiration is a helper method to define mock.On call
//   - memberID string
//   - weekStart string
//   - stats *team.MemberWeeklyStats
//   - expiration time.Duration
func (_e *MockWeeklyStatsStoreInterface_Expecter) SetWithExpiration(memberID interface{}, weekStart interface{}, stats interface{}, expiration interface{}) *MockWeeklyStatsStoreInterface_SetWithExpiration_Call {
	return &MockWeeklyStatsStoreInterface_SetWithExpiration_Call{Call: _e.mock.On("SetWithExpiration", memberID, weekStart, stats, expiration)}
}

func (_c *MockWeeklyStatsStoreInterface_SetWithExpiration_Call) Run(run func(memberID string, weekStart string, stats *team.MemberWeeklyStats, expiration time.Duration)) *MockWeeklyStatsStoreInterface_SetWithExpiration_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 *team.MemberWeeklyStats
		if args[2] != nil {
			arg2 = args[2].(*team.MemberWeeklyStats)
		}
		var arg3 time.Duration
		if args[3] != nil {
			arg3 = args[3].(time.Duration)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockWeeklyStatsStoreInterface_SetWithExpiration_Call) Return(err error) *MockWeeklyStatsStoreInterface_SetWithExpiration_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockWeeklyStatsStoreInterface_SetWithExpiration_Call) RunAndReturn(run func(memberID string, weekStart string, stats *team.MemberWeeklyStats, expiration time.Duration) error) *MockWeeklyStatsStoreInterface_SetWithExpiration_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockHTTPClientInterface creates a new instance of MockHTTPClientInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockHTTPClientInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockHTTPClientInterface {
	mock := &MockHTTPClientInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockHTTPClientInterface is an autogenerated mock type for the HTTPClientInterface type
type MockHTTPClientInterface struct {
	mock.Mock
}

type MockHTTPClientInterface_Expecter struct {
	mock *mock.Mock
}

func (_m *MockHTTPClientInterface) EXPECT() *MockHTTPClientInterface_Expecter {
	return &MockHTTPClientInterface_Expecter{mock: &_m.Mock}
}

// Do provides a mock function for the type MockHTTPClientInterface
func (_mock *MockHTTPClientInterface) Do(req *http.Request) (*http.Response, error) {
	ret := _mock.Called(req)

	if len(ret) == 0 {
		panic("no return value specified for Do")
	}

	var r0 *http.Response
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(*http.Request) (*http.Response, error)); ok {
		return returnFunc(req)
	}
	if returnFunc, ok := ret.Get(0).(func(*http.Request) *http.Response); ok {
		r0 = returnFunc(req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*http.Response)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(*http.Request) error); ok {
		r1 = returnFunc(req)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockHTTPClientInterface_Do_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Do'
type MockHTTPClientInterface_Do_Call struct {
	*mock.Call
}

// Do is a helper method to define mock.On call
//   - req *http.Request
func (_e *MockHTTPClientInterface_Expecter) Do(req interface{}) *MockHTTPClientInterface_Do_Call {
	return &MockHTTPClientInterface_Do_Call{Call: _e.mock.On("Do", req)}
}

func (_c *MockHTTPClientInterface_Do_Call) Run(run func(req *http.Request)) *MockHTTPClientInterface_Do_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *http.Request
		if args[0] != nil {
			arg0 = args[0].(*http.Request)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockHTTPClientInterface_Do_Call) Return(response *http.Response, err error) *MockHTTPClientInterface_Do_Call {
	_c.Call.Return(response, err)
	return _c
}

func (_c *MockHTTPClientInterface_Do_Call) RunAndReturn(run func(req *http.Request) (*http.Response, error)) *MockHTTPClientInterface_Do_Call {
	_c.Call.Return(run)
	return _c
}
