// Code generated by swaggo/swag. DO NOT EDIT.

package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/notifications": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "通知"
                ],
                "summary": "创建通知",
                "parameters": [
                    {
                        "description": "通知信息",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github_com_cocursor_backend_internal_application_notification.CreateNotificationDTO"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_cocursor_backend_internal_interfaces_http_response.Response"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/github_com_cocursor_backend_internal_interfaces_http_response.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/stats/acceptance-rate": {
            "get": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "统计"
                ],
                "summary": "获取 AI 代码接受率统计",
                "parameters": [
                    {
                        "type": "string",
                        "description": "开始日期，格式 YYYY-MM-DD，默认最近 7 天",
                        "name": "start_date",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "结束日期，格式 YYYY-MM-DD，默认今天",
                        "name": "end_date",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/github_com_cocursor_backend_internal_interfaces_http_response.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "array",
                                            "items": {
                                                "$ref": "#/definitions/github_com_cocursor_backend_internal_domain_cursor.DailyAcceptanceStats"
                                            }
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/github_com_cocursor_backend_internal_interfaces_http_response.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/github_com_cocursor_backend_internal_interfaces_http_response.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/stats/conversation-overview": {
            "get": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "统计"
                ],
                "summary": "获取对话统计概览",
                "parameters": [
                    {
                        "type": "string",
                        "description": "项目路径，如 D:/code/cocursor（可选，如果不提供则尝试自动检测）",
                        "name": "project_path",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/github_com_cocursor_backend_internal_interfaces_http_response.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/github_com_cocursor_backend_internal_domain_cursor.ConversationOverview"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/github_com_cocursor_backend_internal_interfaces_http_response.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/github_com_cocursor_backend_internal_interfaces_http_response.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/stats/current-session": {
            "get": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "统计"
                ],
                "summary": "获取当前会话的健康状态",
                "parameters": [
                    {
                        "type": "string",
                        "description": "项目路径，如 D:/code/cocursor（可选，如果不提供则尝试自动检测）",
                        "name": "project_path",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/github_com_cocursor_backend_internal_interfaces_http_response.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/github_com_cocursor_backend_internal_application_cursor.HealthInfo"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/github_com_cocursor_backend_internal_interfaces_http_response.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/github_com_cocursor_backend_internal_interfaces_http_response.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/stats/daily-report": {
            "get": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "统计"
                ],
                "summary": "生成日报",
                "parameters": [
                    {
                        "type": "string",
                        "description": "项目路径，如 D:/code/cocursor（可选，如果不提供则尝试自动检测）",
                        "name": "project_path",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "日期，格式 YYYY-MM-DD，默认今天",
                        "name": "date",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Top N 会话数，默认 5，最大 20",
                        "name": "top_n_sessions",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Top N 文件数，默认 10，最大 50",
                        "name": "top_n_files",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/github_com_cocursor_backend_internal_interfaces_http_response.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/github_com_cocursor_backend_internal_domain_cursor.DailyReport"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/github_com_cocursor_backend_internal_interfaces_http_response.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/github_com_cocursor_backend_internal_interfaces_http_response.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/stats/file-references": {
            "get": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "统计"
                ],
                "summary": "获取文件引用分析",
                "parameters": [
                    {
                        "type": "string",
                        "description": "项目路径，如 D:/code/cocursor（可选，如果不提供则尝试自动检测）",
                        "name": "project_path",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "返回前 N 个文件，默认 10，最大 50，最小 1",
                        "name": "top_n",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/github_com_cocursor_backend_internal_interfaces_http_response.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "array",
                                            "items": {
                                                "$ref": "#/definitions/github_com_cocursor_backend_internal_domain_cursor.FileReference"
                                            }
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/github_com_cocursor_backend_internal_interfaces_http_response.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/github_com_cocursor_backend_internal_interfaces_http_response.ErrorResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "github_com_cocursor_backend_internal_application_cursor.HealthInfo": {
            "type": "object",
            "properties": {
                "entropy": {
                    "description": "熵值",
                    "type": "number"
                },
                "status": {
                    "description": "健康状态",
                    "allOf": [
                        {
                            "$ref": "#/definitions/github_com_cocursor_backend_internal_application_cursor.HealthStatus"
                        }
                    ]
                },
                "warning": {
                    "description": "警告信息（如果有）",
                    "type": "string"
                }
            }
        },
        "github_com_cocursor_backend_internal_application_cursor.HealthStatus": {
            "type": "string",
            "enum": [
                "healthy",
                "sub_healthy",
                "dangerous"
            ],
            "x-enum-varnames": [
                "HealthStatusHealthy",
                "HealthStatusSubHealthy",
                "HealthStatusDangerous"
            ]
        },
        "github_com_cocursor_backend_internal_application_notification.CreateNotificationDTO": {
            "type": "object",
            "required": [
                "message",
                "teamCode",
                "title"
            ],
            "properties": {
                "message": {
                    "type": "string"
                },
                "teamCode": {
                    "type": "string"
                },
                "title": {
                    "type": "string"
                },
                "type": {
                    "type": "integer"
                }
            }
        },
        "github_com_cocursor_backend_internal_domain_cursor.AIUsageSummary": {
            "type": "object",
            "properties": {
                "active_sessions": {
                    "description": "活跃会话数",
                    "type": "integer"
                },
                "total_chats": {
                    "description": "总对话数",
                    "type": "integer"
                },
                "total_generations": {
                    "description": "总生成数",
                    "type": "integer"
                }
            }
        },
        "github_com_cocursor_backend_internal_domain_cursor.CodeChangeSummary": {
            "type": "object",
            "properties": {
                "files_changed": {
                    "description": "变更文件数",
                    "type": "integer"
                },
                "total_lines_added": {
                    "description": "总添加行数",
                    "type": "integer"
                },
                "total_lines_removed": {
                    "description": "总删除行数",
                    "type": "integer"
                }
            }
        },
        "github_com_cocursor_backend_internal_domain_cursor.ConversationOverview": {
            "type": "object",
            "properties": {
                "active_sessions": {
                    "description": "活跃会话数",
                    "type": "integer"
                },
                "latest_chat_time": {
                    "description": "最近对话时间（ISO 8601）",
                    "type": "string"
                },
                "time_since_last_gen": {
                    "description": "距离最近生成的时间（分钟）",
                    "type": "number"
                },
                "total_chats": {
                    "description": "总对话数",
                    "type": "integer"
                },
                "total_generations": {
                    "description": "总生成数",
                    "type": "integer"
                }
            }
        },
        "github_com_cocursor_backend_internal_domain_cursor.DailyAcceptanceStats": {
            "type": "object",
            "properties": {
                "composerAcceptedLines": {
                    "description": "Composer 接受的代码行数",
                    "type": "integer"
                },
                "composerSuggestedLines": {
                    "description": "Composer 建议的代码行数",
                    "type": "integer"
                },
                "composer_acceptance_rate": {
                    "description": "Composer 接受率（百分比，计算字段）",
                    "type": "number"
                },
                "date": {
                    "description": "日期 YYYY-MM-DD",
                    "type": "string"
                },
                "tabAcceptedLines": {
                    "description": "Tab 接受的代码行数",
                    "type": "integer"
                },
                "tabSuggestedLines": {
                    "description": "Tab 建议的代码行数",
                    "type": "integer"
                },
                "tab_acceptance_rate": {
                    "description": "Tab 接受率（百分比，计算字段）",
                    "type": "number"
                }
            }
        },
        "github_com_cocursor_backend_internal_domain_cursor.DailyReport": {
            "type": "object",
            "properties": {
                "acceptance_rate": {
                    "description": "接受率统计",
                    "allOf": [
                        {
                            "$ref": "#/definitions/github_com_cocursor_backend_internal_domain_cursor.DailyAcceptanceStats"
                        }
                    ]
                },
                "ai_usage": {
                    "description": "AI 使用统计",
                    "allOf": [
                        {
                            "$ref": "#/definitions/github_com_cocursor_backend_internal_domain_cursor.AIUsageSummary"
                        }
                    ]
                },
                "code_changes": {
                    "description": "代码变更汇总",
                    "allOf": [
                        {
                            "$ref": "#/definitions/github_com_cocursor_backend_internal_domain_cursor.CodeChangeSummary"
                        }
                    ]
                },
                "date": {
                    "description": "日期 YYYY-MM-DD",
                    "type": "string"
                },
                "top_files": {
                    "description": "Top N 文件引用",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/github_com_cocursor_backend_internal_domain_cursor.FileReference"
                    }
                },
                "top_sessions": {
                    "description": "Top N 会话",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/github_com_cocursor_backend_internal_domain_cursor.SessionSummary"
                    }
                },
                "workspace_id": {
                    "description": "工作区 ID",
                    "type": "string"
                }
            }
        },
        "github_com_cocursor_backend_internal_domain_cursor.FileReference": {
            "type": "object",
            "properties": {
                "file_name": {
                    "description": "文件名",
                    "type": "string"
                },
                "file_type": {
                    "description": "文件类型（从扩展名推断）",
                    "type": "string"
                },
                "reference_count": {
                    "description": "引用次数",
                    "type": "integer"
                }
            }
        },
        "github_com_cocursor_backend_internal_domain_cursor.SessionSummary": {
            "type": "object",
            "properties": {
                "composer_id": {
                    "description": "会话 ID",
                    "type": "string"
                },
                "duration": {
                    "description": "持续时间（分钟）",
                    "type": "number"
                },
                "entropy": {
                    "description": "熵值",
                    "type": "number"
                },
                "files_changed": {
                    "description": "变更文件数",
                    "type": "integer"
                },
                "name": {
                    "description": "会话名称",
                    "type": "string"
                },
                "total_lines": {
                    "description": "总变更行数",
                    "type": "integer"
                }
            }
        },
        "github_com_cocursor_backend_internal_interfaces_http_response.ErrorResponse": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer"
                },
                "detail": {
                    "type": "string"
                },
                "message": {
                    "type": "string"
                }
            }
        },
        "github_com_cocursor_backend_internal_interfaces_http_response.Response": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer"
                },
                "data": {},
                "message": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:19960",
	BasePath:         "/api/v1",
	Schemes:          []string{"http"},
	Title:            "cocursor Daemon API",
	Description:      "cocursor 守护进程 API 服务",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
